/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package coroutine

import kotlinx.coroutines.GlobalScope
import kotlinx.coroutines.launch

fun main(args: Array<String>) {
    println("start")
    GlobalScope.launch {
        println("coroutine!")
    }
    Thread.sleep(2000) // wait for 2 seconds
    println("end")

    /*実行結果：
    * start
      coroutine!
      end
    *
    * */
}
