/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package coroutine

import kotlinx.coroutines.GlobalScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch

fun main(args: Array<String>) {
    println("Start")

    // Start a coroutine
    GlobalScope.launch {
        delay(1000)//delay() function that's like Thread.sleep(), but better: it doesn't block a thread, but only suspends the coroutine itself.
        println("Hello")
    }

    Thread.sleep(2000) // wait for 2 seconds
    println("Stop")

    /*実行結果：
    * start
      coroutine!
      end
    *
    * */
}
